node('appserver'){
  try {

    notifyStarted()

    stage('Git Checkout'){
        git credentialsId: 'kevinwood75', url: 'https://github.com/kevinwood75/react-learing.git', branch: 'master'
    }

/*  stage('Remove old Container release'){
        sh 'docker stop woodezfi-ui'
    } */

    stage('Build Docker Image'){
        sh 'cd dev && docker build -t sample:dev .'
    }
/*    stage('Push Docker Image'){
        withCredentials([string(credentialsId: 'docker-pwd', variable: 'dockerhub')]) {
           sh "docker login -u kwood475 -p ${dockerhub}"
        }
        sh 'docker push kwood475/sample:dev'
    }*/

    stage('Release Container on Server'){
        sh 'docker run --name woodezfi-ui -itd --rm -v ${PWD}:/app -v /app/node_modules -p 3001:3000 -e CHOKIDAR_USEPOLLING=true sample:dev'

    }
    notifySuccessful()
  } catch (e) {
      currentBuild.result = "FAILED"
      notifyFailed()
      throw e
  }
}

def notifyStarted() {
  slackSend (color: '#FFFF00', message: "STARTED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
}

def notifySuccessful() {
  slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
}

def notifyFailed() {
  slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
}
